name: chab
description: "A chat app made with flutter and firebase."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5

  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  flutter_bloc: ^9.1.0
  shared_preferences: ^2.3.2

  user_repository:
    path: packages/user_repository

  room_repository:
    path: packages/room_repository

  es_client_repository:
    path: packages/es_client_repository
    
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
